name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Why is this feature needed? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: objectives
    attributes:
      label: Objectives
      description: What are the key goals for this feature?
    validations:
      required: true
  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Any technical implementation details to consider
  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      options:
        - Small
        - Medium
        - Large
    validations:
      required: true
  - type: input
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies on other issues (e.g., "Issue #123")